import streamlit as st
import numpy as np
import plotly.graph_objects as go
import google.genai as genai
import os

"""
After compilation, run:
$ streamlit run ofdm_impairments.py
"""

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="OFDM Signal Impairments",
    page_icon="📡",
    layout="centered",
    initial_sidebar_state="expanded"
)

# --- CUSTOM CSS FOR "TEXTBOOK" LOOK ---
st.markdown("""
<style>
    .main .block-container {
        padding-top: 2rem;
        max_width: 1200px;
    }
    h1 { font-family: 'Helvetica', sans-serif; font-weight: 800; color: #4fc3f7; }
    h2 { font-family: 'Georgia', serif; font-weight: 600; color: #e1f5fe; border-bottom: 1px solid #37474f; padding-bottom: 10px; }
    h3 { font-family: 'Helvetica', sans-serif; font-weight: 600; color: #b3e5fc; margin-top: 20px; }
    .stApp { background-color: #0f172a; color: #e2e8f0; }
    .concept-card {
        background-color: #1e293b;
        border-left: 5px solid #06b6d4;
        padding: 20px;
        border-radius: 5px;
        margin-bottom: 20px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.3);
    }
    .latex-container {
        background-color: #1e293b;
        padding: 15px;
        border-radius: 8px;
        text-align: center;
        margin: 20px 0;
        border: 1px solid #334155;
    }
</style>
""", unsafe_allow_html=True)

# --- SESSION STATE INITIALIZATION ---
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []
if "messages" not in st.session_state:
    # Initialize with a welcome message
    st.session_state.messages = [{"role": "assistant",
                                  "content": "Hello! I am your OFDM Research Assistant. I can derive equations, explain physical phenomena, or generate quiz questions. How can I help?"}]

# --- SIDEBAR NAVIGATION ---
with st.sidebar:
    st.title("📡 SignalLab")
    st.caption("OFDM Impairment Analysis")

    selected_page = st.radio(
        "Navigation",
        ["Overview", "CFO Analysis", "SFO Correction", "IQ Imbalance", "AI Assistant"],
        index=0
    )

    st.divider()

    # API Key Handling
    api_key = st.text_input("Gemini API Key", type="password", placeholder="Paste key here to enable AI")
    if api_key:
        os.environ["GOOGLE_API_KEY"] = api_key
        genai.configure(api_key=api_key)

    st.info("System Status: LIVE ENV\nModel: Gemini 2.0 Flash")


# --- HELPER FUNCTIONS ---

def get_gemini_response(prompt):
    """Robust wrapper for Gemini API calls."""
    if not api_key:
        return "⚠️ Please enter a valid Gemini API Key in the sidebar to use the AI Assistant."

    try:
        client = genai.Client()

        response = client.models.generate_content(
            model='gemini-2.0-flash-exp',
            contents=prompt
        )
        #model = genai.GenerativeModel('gemini-2.0-flash-exp')
        #response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Error connecting to AI: {str(e)}"


def plot_config(fig):
    """Apply consistent styling to Plotly figures."""
    fig.update_layout(
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(30, 41, 59, 0.5)',
        font=dict(color='#cbd5e1'),
        margin=dict(l=20, r=20, t=40, b=20),
        xaxis=dict(gridcolor='#334155', zerolinecolor='#94a3b8'),
        yaxis=dict(gridcolor='#334155', zerolinecolor='#94a3b8'),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )
    return fig


# --- PAGE CONTENT ---

if selected_page == "Overview":
    st.title("OFDM System Overview")

    tab1, tab2 = st.tabs(["📘 Theory & Math", "📈 Interactive Simulation"])

    with tab1:
        st.markdown("""
        <div class="concept-card">
            <h3>Core Concept: The Orthogonality Principle</h3>
            <p>OFDM packs data onto parallel subcarriers. Unlike classical FDM, these subcarriers overlap spectrally. 
            We can separate them because they are <strong>orthogonal</strong>: at the exact sampling instant of the peak of one subcarrier, 
            all others are crossing zero.</p>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("### 1. Signal Generation (IDFT)")
        st.write(
            "The discrete-time baseband signal is generated by taking the IDFT of a block of $N$ QAM symbols $X_k$.")
        st.latex(r"x[n] = \frac{1}{\sqrt{N}} \sum_{k=0}^{N-1} X_k e^{j2\pi k n / N}, \quad 0 \leq n < N")

        st.markdown("### 2. The Channel & Cyclic Prefix")
        st.write(
            "To combat multipath delay ($h[n]$) which causes linear convolution and destroys orthogonality, we add a Cyclic Prefix (CP). "
            "This converts linear convolution to circular convolution ($\circledast$)."
        )
        st.latex(r"y[n] = x[n] \circledast h[n] + w[n]")

        st.markdown("### 3. Reception (DFT)")
        st.write(
            "The Circular Convolution Theorem states that circular convolution in time is equivalent to multiplication in frequency. "
            "This diagonalizes the channel.")
        st.latex(r"Y_k = \text{DFT}\{y\} = H_k X_k + W_k")

        st.info(
            "💡 **Key Takeaway:** If orthogonality holds, data recovery is a simple scalar division: $\hat{X}_k = Y_k / H_k$. "
            "RF impairments break this diagonal structure.")

    with tab2:
        st.subheader("Spectral Orthogonality Visualization")
        st.write("Observe how the peak of the **Target Subcarrier** aligns with the nulls of its neighbors.")

        # Generate Sinc Data
        x = np.linspace(-4, 4, 500)


        def sinc(val):
            return np.sinc(val)  # numpy sinc is sin(pi*x)/(pi*x)

        y_k = np.abs(sinc(x))
        y_km1 = np.abs(sinc(x + 1))
        y_kp1 = np.abs(sinc(x - 1))

        fig = go.Figure()
        fig.add_trace(
            go.Scatter(x=x, y=y_km1, mode='lines', name='Subcarrier k-1', line=dict(color='#64748b', width=2)))
        fig.add_trace(
            go.Scatter(x=x, y=y_k, mode='lines', name='Subcarrier k (Target)', line=dict(color='#06b6d4', width=4),
                       fill='tozeroy', fillcolor='rgba(6,182,212,0.1)'))
        fig.add_trace(
            go.Scatter(x=x, y=y_kp1, mode='lines', name='Subcarrier k+1', line=dict(color='#64748b', width=2)))

        fig.update_layout(title="Frequency Domain Representation", xaxis_title="Frequency (Normalized)",
                          yaxis_title="Amplitude")
        st.plotly_chart(plot_config(fig), use_container_width=True)

elif selected_page == "CFO Analysis":
    st.title("Carrier Frequency Offset (CFO)")

    tab1, tab2 = st.tabs(["📘 Theory & Math", "📈 Interactive Simulation"])

    with tab1:
        st.markdown("""
        <div class="concept-card" style="border-left-color: #3b82f6;">
            <h3>Physical Intuition: The Spinning Record</h3>
            <p>Imagine drawing a map on a record player. If the player spins slightly faster than expected, your drawing rotates over time. 
            In OFDM, frequency mismatch ($\Delta f$) manifests as a time-varying phase, causing the constellation to spin (Common Phase Error) 
            and eventually blur (Inter-Carrier Interference).</p>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("### Mathematical Model")
        st.write(
            "Let $\epsilon = \Delta f \cdot N T_s$ be the normalized frequency offset. The received signal acquires a phase ramp:"
        )
        st.latex(r"y[n] = x[n] e^{j 2\pi \epsilon n / N} + w[n]")

        st.markdown("### Effect on Subcarriers (ICI)")
        st.write("In the frequency domain, this multiplication in time becomes convolution (leakage) in frequency:")
        st.latex(
            r"Y_k = \underbrace{X_k S(0)}_{\text{Attenuated Signal}} + \underbrace{\sum_{m \neq k} X_m S(k-m)}_{\text{ICI}} + W_k"
        )

        st.markdown("### Estimator: Schmidl & Cox")
        st.write(
            "Using a training symbol with two identical halves $[A, A]$, the phase difference between halves reveals $\epsilon$."
        )
        st.latex(r"\hat{\epsilon} = \frac{1}{\pi} \angle \left( \sum_{m=0}^{N/2-1} y^*[m] y[m+N/2] \right)")

    with tab2:
        st.subheader("CFO Simulation")

        epsilon = st.slider("Normalized Offset ($\epsilon$)", min_value=0.0, max_value=0.6, value=0.05, step=0.01)

        if epsilon > 0.5:
            st.error("⚠️ Warning: $\epsilon > 0.5$ causes phase ambiguity (Schmidl & Cox limit).")

        # Generate Constellation
        np.random.seed(42)
        n_sym = 500
        # 16-QAM Grid
        levels = np.array([-3, -1, 1, 3])
        real = np.random.choice(levels, n_sym)
        imag = np.random.choice(levels, n_sym)

        # Apply Rotation + ICI Noise
        # Rotation is deterministic based on epsilon
        # ICI is modeled as random noise dependent on epsilon magnitude
        rotation = epsilon * np.pi
        ici_power = (epsilon * 1.5) ** 2

        # Apply rotation
        complex_sym = (real + 1j * imag) * np.exp(1j * rotation)

        # Add ICI/Noise
        noise = (np.random.randn(n_sym) + 1j * np.random.randn(n_sym)) * np.sqrt(0.01 + ici_power)
        rx_sym = complex_sym #+ noise

        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=np.real(rx_sym), y=np.imag(rx_sym),
            mode='markers', marker=dict(color='#3b82f6', size=8, opacity=0.7, line=dict(width=1, color='white')),
            name='Received Symbols'
        ))

        fig.update_layout(
            title=f"Constellation with CFO (ε={epsilon})",
            xaxis=dict(range=[-6, 6], title="In-Phase (I)"),
            yaxis=dict(range=[-6, 6], title="Quadrature (Q)", scaleanchor="x", scaleratio=1),
            width=700, height=700
        )
        st.plotly_chart(plot_config(fig), use_container_width=True)

elif selected_page == "SFO Correction":
    st.title("Sampling Frequency Offset (SFO)")

    tab1, tab2 = st.tabs(["📘 Theory & Math", "📈 Interactive Simulation"])

    with tab1:
        st.markdown("""
        <div class="concept-card" style="border-left-color: #f59e0b;">
            <h3>Physical Intuition: The Stretching Ruler</h3>
            <p>SFO happens when the receiver's ADC clock ticks at a slightly different rate than the transmitter. 
            This is a time-dilation effect. If you sample later and later, you introduce a growing time delay. 
            <strong>Key Result:</strong> A delay in Time = A Phase Ramp in Frequency.</p>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("### Mathematical Derivation")
        st.write(
            "Let $\delta$ be the sampling clock offset (ppm). The phase rotation $\phi_{k,l}$ for subcarrier $k$ at symbol $l$ is:"
        )
        st.latex(r"\phi_{k,l} \approx -2\pi \cdot k \cdot \delta \cdot \frac{T_{symbol}}{T_{sample}} \cdot l")

        st.markdown("### Characteristics")
        st.write("1. **Slope in Frequency ($k$):** The phase error increases linearly with subcarrier index.")
        st.write("2. **Drift in Time ($l$):** The slope gets steeper for subsequent symbols.")

    with tab2:
        st.subheader("SFO Phase Error Visualization")

        ppm = st.slider("Clock Drift (ppm)", min_value=-100, max_value=100, value=20, step=5)

        # Generate SFO Data
        k = np.arange(-32, 32)
        # Slope depends on ppm
        slope = ppm * 0.05
        phase_error = k * slope

        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=k, y=phase_error,
            mode='lines+markers',
            line=dict(color='#f59e0b', width=3),
            marker=dict(size=6),
            name='Phase Error'
        ))

        fig.update_layout(
            title=f"Phase Error vs Subcarrier Index ({ppm} ppm)",
            xaxis_title="Subcarrier Index (k)",
            yaxis_title="Phase Rotation (degrees)",
            yaxis=dict(range=[-180, 180])
        )
        st.plotly_chart(plot_config(fig), use_container_width=True)

elif selected_page == "IQ Imbalance":
    st.title("IQ Imbalance")

    tab1, tab2 = st.tabs(["📘 Theory & Math", "📈 Interactive Simulation"])

    with tab1:
        st.markdown("""
        <div class="concept-card" style="border-left-color: #d946ef;">
            <h3>Physical Intuition: The Broken Compass</h3>
            <p>We transmit using two physical paths: I (Real) and Q (Imaginary). Ideally, these are perfectly orthogonal ($90^\circ$). 
            Hardware imperfections (Gain mismatch $g$ or Phase skew $\phi$) distort the coordinate system.
            <strong>Consequence:</strong> Mirror Frequency Interference ($+k$ leaks into $-k$).</p>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("### Mixer Model")
        st.latex(r"y_{bb}(t) = I(t) + j \cdot g(Q(t)\cos\phi - I(t)\sin\phi)")

        st.markdown("### Equivalent Baseband Model")
        st.write("The output is a weighted sum of the signal and its conjugate:")
        st.latex(r"y(t) = \alpha x(t) + \beta x^*(t)")
        st.write("Where $\\beta$ represents the leakage from the image frequency.")

        st.markdown("### Frequency Domain")
        st.latex(r"Y_k = \alpha X_k + \beta^* X_{-k}^*")

    with tab2:
        st.subheader("IQ Imbalance Visualization")

        col1, col2 = st.columns(2)
        with col1:
            gain_db = st.slider("Gain Imbalance (dB)", 0.0, 6.0, 3.0, 0.1)
        with col2:
            phase_deg = st.slider("Phase Imbalance (deg)", 0.0, 30.0, 15.0, 1.0)

        # Simulation
        np.random.seed(42)
        n_pts = 1000
        levels = np.array([-3, -1, 1, 3])
        i_tx = np.random.choice(levels, n_pts)
        q_tx = np.random.choice(levels, n_pts)

        # Apply Imbalance
        g = 10 ** (gain_db / 20.0)
        phi_rad = np.deg2rad(phase_deg)

        # Model: I is ref, Q is distorted
        i_rx = i_tx
        q_rx = g * (q_tx * np.cos(phi_rad) - i_tx * np.sin(phi_rad))

        # Add thermal noise
        ##i_rx += np.random.normal(0, 0.15, n_pts)
        ##q_rx += np.random.normal(0, 0.15, n_pts)

        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=i_rx, y=q_rx,
            mode='markers',
            marker=dict(color='#d946ef', size=6, opacity=0.6),
            name='Distorted Symbols'
        ))

        # Add Reference Lines
        fig.add_shape(type="line", x0=-8, y0=0, x1=8, y1=0, line=dict(color="gray", dash="dot"))
        fig.add_shape(type="line", x0=0, y0=-8, x1=0, y1=8, line=dict(color="gray", dash="dot"))

        fig.update_layout(
            title=f"IQ Constellation (G={gain_db}dB, φ={phase_deg}°)",
            xaxis=dict(range=[-8, 8], title="In-Phase (I)"),
            yaxis=dict(range=[-8, 8], title="Quadrature (Q)", scaleanchor="x", scaleratio=1),
            width=700, height=700
        )
        st.plotly_chart(plot_config(fig), use_container_width=True)

elif selected_page == "AI Assistant":
    st.title("🤖 Research Assistant")
    st.caption("Powered by Gemini 2.0 Flash")

    # Display Chat History
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # Chat Input
    if prompt := st.chat_input("Ask about OFDM math, Schmidl & Cox, or request a quiz..."):
        # Display user message
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Get and display AI response
        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                response_text = get_gemini_response(
                    f"Role: Expert Wireless Communications Professor. Topic: OFDM Impairments. User Question: {prompt}. Please use LaTeX for math (wrapped in $). Keep it concise and technical.")
                st.markdown(response_text)
                st.session_state.messages.append({"role": "assistant", "content": response_text})

    # Quick Quiz Button
    if st.button("Generate Quiz Question"):
        prompt = "Generate a difficult multiple-choice question about OFDM CFO, SFO, or IQ Imbalance. Provide the question, options, and then a hidden detailed explanation using math."
        # Inject into chat flow
        st.session_state.messages.append({"role": "user", "content": "Generate Quiz Question"})
        with st.chat_message("assistant"):
            with st.spinner("Generating Quiz..."):
                response_text = get_gemini_response(prompt)
                st.markdown(response_text)
                st.session_state.messages.append({"role": "assistant", "content": response_text})